# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a2c0c1ca7f229c8438b6ec44b4a44b9bc32d130397e7e839a96fa87f3d9987bebf3761c3c427f8993855ede7584fd93a1321daca5e87e5db98a10fb2572402d

test:
  secret_key_base: 4c0214c4e833735ba17b178b294d6532b5b8021c9e8de7a0b49e2861d5f9dfdea4c9bafd2a150a732aba9c24b6622add04914f9c1f226d603e0d38f24100ab21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
